FROM registry.access.redhat.com/ubi8/ubi:latest as builder
RUN dnf install -y make git golang unzip gcc
RUN git clone https://github.com/tsliwowicz/go-wrk.git --depth=1
RUN cd go-wrk && go build -o go-wrk
RUN git clone https://github.com/wg/wrk.git --depth=1
RUN cd wrk && make -j $(nproc)

FROM registry.access.redhat.com/ubi8/ubi:latest
RUN dnf install -y iproute procps-ng
COPY --from=builder /go-wrk/go-wrk /usr/bin/go-wrk
COPY --from=builder /wrk/wrk /usr/bin/wrk
COPY json.lua json.lua
RUN curl -sS -L https://github.com/rsevilla87/hloader/releases/download/v0.2.1/hloader-Linux-v0.2.1-$(arch | sed s/aarch64/arm64/).tar.gz | tar xz -C /usr/bin/
